class_name SpellShapeData
extends RefCounted

const SHAPES := {
	"circle": {
		"id": "circle",
		"display_name": "Circle",
		"description": "A stable and versatile form.",
		"visual_shape": "circle",
		"base_color": Color(0.72, 0.48, 1.0),
		"short_summary": "Balanced and stable.",
		"strengths": "Reliable size, speed, and damage.",
		"weaknesses": "No extreme specialization.",
		"scaling_keywords": "balanced damage, speed, size",
		"preview_id": "circle",
		"available": true,
		"damage_multiplier": 1.0,
		"projectile_speed_multiplier": 1.0,
		"fire_interval_multiplier": 1.0,
		"size_multiplier": 1.0,
		"pierce_bonus": 0,
		"duration_multiplier": 1.0,
		"area_multiplier": 1.0,
		"chain_range_multiplier": 1.0,
		"chain_jump_range_multiplier": 1.0,
		"chain_visual_width_multiplier": 1.0,
		"area_size_multiplier": 1.0,
		"area_duration_multiplier": 1.0,
		"area_tick_interval_multiplier": 1.0,
		"area_damage_multiplier": 1.0,
		"slash_range_multiplier": 1.0,
		"slash_size_multiplier": 1.0,
		"slash_width_multiplier": 1.0,
		"slash_damage_multiplier": 1.0,
		"slash_arc_multiplier": 1.15,
		"wave_speed_multiplier": 1.0,
		"wave_width_multiplier": 1.0,
		"wave_damage_multiplier": 1.0,
		"wave_lifetime_multiplier": 1.0,
		"modifiers_text": "Balanced damage, speed, and size.",
	},
	"triangle": {
		"id": "triangle",
		"display_name": "Triangle",
		"description": "A fast and precise form.",
		"visual_shape": "triangle",
		"base_color": Color(1.0, 0.52, 0.38),
		"short_summary": "Fast and aggressive.",
		"strengths": "Quick casts and focused pressure.",
		"weaknesses": "Smaller spell patterns.",
		"scaling_keywords": "speed, cadence, focused damage",
		"preview_id": "triangle",
		"available": true,
		"damage_multiplier": 0.92,
		"projectile_speed_multiplier": 1.28,
		"fire_interval_multiplier": 0.94,
		"size_multiplier": 0.86,
		"pierce_bonus": 0,
		"duration_multiplier": 1.0,
		"area_multiplier": 0.9,
		"chain_range_multiplier": 1.16,
		"chain_jump_range_multiplier": 1.08,
		"chain_visual_width_multiplier": 0.82,
		"area_size_multiplier": 0.84,
		"area_duration_multiplier": 0.9,
		"area_tick_interval_multiplier": 0.82,
		"area_damage_multiplier": 1.16,
		"slash_range_multiplier": 0.95,
		"slash_size_multiplier": 0.82,
		"slash_width_multiplier": 0.74,
		"slash_damage_multiplier": 1.14,
		"slash_arc_multiplier": 0.72,
		"wave_speed_multiplier": 1.2,
		"wave_width_multiplier": 0.72,
		"wave_damage_multiplier": 0.94,
		"wave_lifetime_multiplier": 0.92,
		"modifiers_text": "+28% speed, -8% damage, smaller projectiles.",
	},
	"square": {
		"id": "square",
		"display_name": "Square",
		"description": "A dense and impactful form.",
		"visual_shape": "square",
		"base_color": Color(0.42, 0.88, 0.64),
		"short_summary": "Heavy and wide.",
		"strengths": "Large, durable spell patterns.",
		"weaknesses": "Slower casts and projectiles.",
		"scaling_keywords": "damage, area, durability",
		"preview_id": "square",
		"available": true,
		"damage_multiplier": 1.28,
		"projectile_speed_multiplier": 0.8,
		"fire_interval_multiplier": 1.1,
		"size_multiplier": 1.32,
		"pierce_bonus": 0,
		"duration_multiplier": 1.12,
		"area_multiplier": 1.2,
		"chain_range_multiplier": 0.9,
		"chain_jump_range_multiplier": 0.84,
		"chain_visual_width_multiplier": 1.3,
		"area_size_multiplier": 1.26,
		"area_duration_multiplier": 1.16,
		"area_tick_interval_multiplier": 1.12,
		"area_damage_multiplier": 1.1,
		"slash_range_multiplier": 1.05,
		"slash_size_multiplier": 1.22,
		"slash_width_multiplier": 1.28,
		"slash_damage_multiplier": 1.12,
		"slash_arc_multiplier": 0.92,
		"wave_speed_multiplier": 0.76,
		"wave_width_multiplier": 1.28,
		"wave_damage_multiplier": 1.18,
		"wave_lifetime_multiplier": 1.12,
		"modifiers_text": "+28% damage, larger and slower projectiles.",
	},
	"diamond": {
		"id": "diamond",
		"display_name": "Diamond Shape",
		"description": "A rapid Spell Shape for fast, precise casts.",
		"visual_shape": "diamond",
		"base_color": Color(0.36, 0.92, 0.94),
		"short_summary": "Precise and quick.",
		"strengths": "Fast rhythm and focused output.",
		"weaknesses": "Lower direct damage.",
		"scaling_keywords": "cadence, speed, precision",
		"preview_id": "diamond",
		"available": true,
		"damage_multiplier": 0.9,
		"projectile_speed_multiplier": 1.16,
		"fire_interval_multiplier": 0.82,
		"size_multiplier": 0.9,
		"pierce_bonus": 0,
		"duration_multiplier": 0.92,
		"area_multiplier": 0.94,
		"chain_range_multiplier": 1.08,
		"chain_jump_range_multiplier": 1.1,
		"chain_visual_width_multiplier": 0.9,
		"area_size_multiplier": 0.9,
		"area_duration_multiplier": 0.9,
		"area_tick_interval_multiplier": 0.88,
		"area_damage_multiplier": 0.94,
		"slash_range_multiplier": 1.06,
		"slash_size_multiplier": 0.88,
		"slash_width_multiplier": 0.84,
		"slash_damage_multiplier": 0.92,
		"slash_arc_multiplier": 1.05,
		"wave_speed_multiplier": 1.1,
		"wave_width_multiplier": 0.9,
		"wave_damage_multiplier": 0.9,
		"wave_lifetime_multiplier": 0.92,
		"modifiers_text": "+18% cast rhythm, +16% speed, -10% damage.",
	},
	"star": {
		"id": "star",
		"display_name": "Star",
		"description": "Spell Shape reserved for future matrices.",
		"visual_shape": "star",
		"available": false,
		"coming_soon": true,
		"short_summary": "Chaotic multi-hit form.",
		"strengths": "Future multi-hit patterning.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "fragments, cadence, multi-hit",
		"preview_id": "generic",
	},
	"pentagon": {
		"id": "pentagon",
		"display_name": "Pentagon",
		"description": "Spell Shape reserved for future matrices.",
		"visual_shape": "pentagon",
		"available": false,
		"coming_soon": true,
		"short_summary": "Experimental matrix pattern.",
		"strengths": "Future structural spell patterns.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "structure, size, durability",
		"preview_id": "generic",
	},
	"hexagon": {
		"id": "hexagon",
		"display_name": "Hexagon",
		"description": "Future Spell Shape for structured patterns.",
		"visual_shape": "hexagon",
		"available": false,
		"coming_soon": true,
		"short_summary": "Structured six-sided patterns.",
		"strengths": "Future stable geometric coverage.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "segments, control, area",
		"preview_id": "generic",
	},
	"spiral": {
		"id": "spiral",
		"display_name": "Spiral",
		"description": "Future Spell Shape for rotating arcane flows.",
		"visual_shape": "spiral",
		"available": false,
		"coming_soon": true,
		"short_summary": "Rotating arcane flow.",
		"strengths": "Future rotational pressure.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "rotation, duration, orbit",
		"preview_id": "generic",
	},
	"line": {
		"id": "line",
		"display_name": "Line",
		"description": "Future Spell Shape for directional patterns.",
		"visual_shape": "line",
		"available": false,
		"coming_soon": true,
		"short_summary": "Directional linear patterns.",
		"strengths": "Future directional precision.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "range, width, speed",
		"preview_id": "generic",
	},
	"fractal": {
		"id": "fractal",
		"display_name": "Fractal",
		"description": "Future Spell Shape for recursive patterns.",
		"visual_shape": "fractal",
		"available": false,
		"coming_soon": true,
		"short_summary": "Recursive geometric patterns.",
		"strengths": "Future recursive scaling.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "splits, recursion, complexity",
		"preview_id": "generic",
	},
}


static func get_data(shape_id: String) -> Dictionary:
	var resolved_id := shape_id if SHAPES.has(shape_id) else "circle"
	return SHAPES[resolved_id].duplicate(true)


static func get_available() -> Array[Dictionary]:
	var shapes: Array[Dictionary] = []
	for shape_id in ["circle", "triangle", "square", "diamond", "star", "pentagon", "hexagon", "spiral", "line", "fractal"]:
		shapes.append(get_data(shape_id))
	return shapes
