class_name SpellDeliveryData
extends RefCounted

const DELIVERIES := {
	"simple_projectile": {
		"id": "simple_projectile",
		"display_name": "Simple Projectile",
		"description": "Fires automatically at the closest enemy.",
		"playstyle_summary": "Reliable direct fire for flexible builds.",
		"short_summary": "Automatic focused fire.",
		"preview_id": "simple_projectile",
		"strengths": "Reliable, flexible, and compatible with most upgrades.",
		"weaknesses": "Needs scaling to clear dense groups efficiently.",
		"scaling_keywords": "count, pierce, ricochet, speed",
		"available": true,
		"tags": ["automatic", "single target"],
	},
	"chain_lightning": {
		"id": "chain_lightning",
		"display_name": "Chain Lightning",
		"description": "Links nearby enemies with falling damage per jump.",
		"playstyle_summary": "Cluster damage through fast chain links.",
		"short_summary": "Links nearby targets.",
		"preview_id": "chain_lightning",
		"strengths": "Excellent against clustered enemies and elemental setups.",
		"weaknesses": "Weaker against isolated targets; damage falls off per jump.",
		"scaling_keywords": "max hits, jump range, falloff, elements",
		"available": true,
		"tags": ["chain", "groups"],
	},
	"area": {
		"id": "area",
		"display_name": "Area Field",
		"description": "Places a temporary field that deals periodic damage.",
		"playstyle_summary": "Persistent zone control for slow or grouped enemies.",
		"short_summary": "Pulsing zone control.",
		"preview_id": "area",
		"strengths": "Controls space and pressures stationary groups.",
		"weaknesses": "Enemies can leave the field before repeated pulses land.",
		"scaling_keywords": "size, duration, tick rate, field count",
		"available": true,
		"tags": ["area", "control"],
	},
	"slash": {
		"id": "slash",
		"display_name": "Slash",
		"description": "Cuts the closest enemies in a fast, instant strike.",
		"playstyle_summary": "Close-range burst with aggressive multi-target scaling.",
		"short_summary": "Instant close-range cut.",
		"preview_id": "slash",
		"strengths": "Satisfying burst against nearby targets.",
		"weaknesses": "Limited early reach and weak against spread-out enemies.",
		"scaling_keywords": "range, targets, cadence, empowered cuts",
		"available": true,
		"tags": ["instant", "nearby target"],
	},
	"persistent_waves": {
		"id": "persistent_waves",
		"display_name": "Persistent Waves",
		"description": "Launches a moving wave toward the nearest enemy.",
		"playstyle_summary": "Directional moving control against lined-up enemies.",
		"short_summary": "Moving directional waves.",
		"preview_id": "persistent_waves",
		"strengths": "Strong through chokepoints and aligned groups.",
		"weaknesses": "Can miss scattered enemies and depends on positioning.",
		"scaling_keywords": "width, speed, lifetime, extra waves",
		"available": true,
		"tags": ["directional", "wave", "groups"],
	},
	"summon": {
		"id": "summon",
		"display_name": "Summoning",
		"description": "Summons temporary Reflections that attack nearby enemies.",
		"playstyle_summary": "Persistent autonomous Reflections with elemental attacks.",
		"short_summary": "Reflections attack nearby targets.",
		"preview_id": "summon",
		"strengths": "Persistent damage, elemental effects, and strong duration scaling.",
		"weaknesses": "Slow setup, weaker burst, and limited early Reflection count.",
		"scaling_keywords": "Reflection count, lifetime, attack speed, damage",
		"available": true,
		"tags": ["summon", "persistent", "echo"],
	},
	"orbitals": {
		"id": "orbitals",
		"display_name": "Orbitals",
		"description": "Future Cast Type for persistent orbiting constructs.",
		"short_summary": "Persistent orbiting constructs.",
		"strengths": "Future persistent coverage.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "orbital count, radius, rotation",
		"preview_id": "generic",
		"available": false,
		"coming_soon": true,
		"tags": ["future", "orbitals"],
	},
	"dual_casting": {
		"id": "dual_casting",
		"display_name": "Dual Casting",
		"description": "Late-game Cast Type that combines two cast patterns.",
		"short_summary": "Combines two cast patterns.",
		"strengths": "Future hybrid spell behavior.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "pairing, cadence, dual upgrades",
		"preview_id": "generic",
		"available": false,
		"coming_soon": true,
		"tags": ["future", "late game"],
	},
	"beam": {
		"id": "beam",
		"display_name": "Beam",
		"description": "Future Cast Type for sustained directional energy.",
		"short_summary": "Sustained directional energy.",
		"strengths": "Future continuous pressure.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "width, duration, focus",
		"preview_id": "generic",
		"available": false,
		"coming_soon": true,
		"tags": ["future", "beam"],
	},
	"mines": {
		"id": "mines",
		"display_name": "Mines",
		"description": "Future Cast Type for delayed arcane traps.",
		"short_summary": "Delayed arcane traps.",
		"strengths": "Future area denial.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "mine count, trigger radius, damage",
		"preview_id": "generic",
		"available": false,
		"coming_soon": true,
		"tags": ["future", "traps"],
	},
	"rain": {
		"id": "rain",
		"display_name": "Rain",
		"description": "Future Cast Type for falling arcane patterns.",
		"short_summary": "Falling arcane patterns.",
		"strengths": "Future broad coverage.",
		"weaknesses": "Not available yet.",
		"scaling_keywords": "drop count, area, cadence",
		"preview_id": "generic",
		"available": false,
		"coming_soon": true,
		"tags": ["future", "rain"],
	},
}


static func get_data(delivery_id: String) -> Dictionary:
	var resolved_id := delivery_id if DELIVERIES.has(delivery_id) else "simple_projectile"
	return DELIVERIES[resolved_id].duplicate(true)


static func get_all() -> Array[Dictionary]:
	var deliveries: Array[Dictionary] = []
	for delivery_id in ["simple_projectile", "chain_lightning", "area", "slash", "persistent_waves", "summon", "orbitals", "dual_casting", "beam", "mines", "rain"]:
		deliveries.append(get_data(delivery_id))
	return deliveries
